export const errorCodes = {
  ERR_LEARN_PERMISSION_INVALID_IP: 701,
  ERR_LEARN_PERMISSION_GUEST_CANNOT_LEARN: 702,
  ERR_LEARN_PERMISSION_END_DATE_OVER_TIME: 703,
  ERR_LEARN_PERMISSION_NOT_INVITE: 704,
  ERR_LEARN_PERMISSION_INVITE_STATUS_DELETED_OR_REJECTED: 705,
  ERR_LEARN_PERMISSION_DEADLINE_OVER: 706,
  ERR_LEARN_PERMISSION_START_DATE_NOT_YET_STARTED: 707,
};
